"""Streamlit application for ML Assignment 2."""
from pathlib import Path
import joblib
import pandas as pd
import streamlit as st
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import (
    accuracy_score, roc_auc_score, precision_score, recall_score,
    f1_score, matthews_corrcoef, confusion_matrix, classification_report
)

PROJECT_DIR = Path(__file__).resolve().parent
MODEL_DIR = PROJECT_DIR / "model"

FEATURE_COLUMNS = [
    "radius1", "texture1", "perimeter1", "area1", "smoothness1",
    "compactness1", "concavity1", "concave_points1", "symmetry1",
    "fractal_dimension1", "radius2", "texture2", "perimeter2", "area2",
    "smoothness2", "compactness2", "concavity2", "concave_points2",
    "symmetry2", "fractal_dimension2", "radius3", "texture3", "perimeter3",
    "area3", "smoothness3", "compactness3", "concavity3",
    "concave_points3", "symmetry3", "fractal_dimension3"
]
REQUIRED_COLUMNS = FEATURE_COLUMNS + ["Diagnosis"]
MODEL_FILES = {
    "Logistic Regression": "logistic_regression.joblib",
    "Decision Tree": "decision_tree.joblib",
    "kNN": "knn.joblib",
    "Naive Bayes": "naive_bayes.joblib",
    "Random Forest (Ensemble)": "random_forest_ensemble.joblib",
}

st.set_page_config(page_title="ML Classification Dashboard", page_icon="🤖", layout="wide")
st.title("🤖 Machine Learning Classification Dashboard")
st.caption("UCI Breast Cancer Wisconsin (Diagnostic) — ML Assignment 2")

st.sidebar.header("1. Upload test data")
uploaded_file = st.sidebar.file_uploader("Upload test_data.csv", type=["csv"])

if uploaded_file is None:
    st.info("Upload the test_data.csv generated by the training script to evaluate the saved models.")
    st.stop()

try:
    df = pd.read_csv(uploaded_file)
except Exception as exc:
    st.error(f"Could not read the CSV file: {exc}")
    st.stop()

missing_columns = [c for c in REQUIRED_COLUMNS if c not in df.columns]
if missing_columns:
    st.error(f"Missing required columns: {missing_columns}")
    st.stop()

if df.empty:
    st.error("The uploaded test data is empty.")
    st.stop()

df["Diagnosis"] = df["Diagnosis"].map({"B": 0, "M": 1, 0: 0, 1: 1})
if df["Diagnosis"].isna().any():
    st.error("Diagnosis must contain B/M (or 0/1) labels.")
    st.stop()

X_test = df[FEATURE_COLUMNS]
y_test = df["Diagnosis"].astype(int)

st.subheader("Uploaded test data")
st.write(f"Rows: **{len(df)}** | Features used: **{len(FEATURE_COLUMNS)}**")
st.dataframe(df.head(10), use_container_width=True)

# Load all saved models.
models = {}
for display_name, filename in MODEL_FILES.items():
    path = MODEL_DIR / filename
    if not path.exists():
        st.error(f"Model file not found: {path.name}. Run model/train_models.py first.")
        st.stop()
    models[display_name] = joblib.load(path)

# Compare all models on the uploaded test data.
all_results = []
for model_name, model in models.items():
    pred = model.predict(X_test)
    prob = model.predict_proba(X_test)[:, 1]
    all_results.append({
        "ML Model Name": model_name,
        "Accuracy": accuracy_score(y_test, pred),
        "AUC": roc_auc_score(y_test, prob),
        "Precision": precision_score(y_test, pred, zero_division=0),
        "Recall": recall_score(y_test, pred, zero_division=0),
        "F1": f1_score(y_test, pred, zero_division=0),
        "MCC": matthews_corrcoef(y_test, pred),
    })

results_df = pd.DataFrame(all_results)
st.subheader("Model comparison")
st.dataframe(
    results_df.style.format({
        "Accuracy": "{:.4f}", "AUC": "{:.4f}", "Precision": "{:.4f}",
        "Recall": "{:.4f}", "F1": "{:.4f}", "MCC": "{:.4f}"
    }),
    use_container_width=True,
)

st.sidebar.header("2. Select model")
selected_model = st.sidebar.selectbox("Model", list(models.keys()))
model = models[selected_model]
pred = model.predict(X_test)
prob = model.predict_proba(X_test)[:, 1]

selected_metrics = {
    "Accuracy": accuracy_score(y_test, pred),
    "AUC": roc_auc_score(y_test, prob),
    "Precision": precision_score(y_test, pred, zero_division=0),
    "Recall": recall_score(y_test, pred, zero_division=0),
    "F1 Score": f1_score(y_test, pred, zero_division=0),
    "MCC Score": matthews_corrcoef(y_test, pred),
}

st.subheader(f"Evaluation metrics — {selected_model}")
metric_cols = st.columns(6)
for column, (name, value) in zip(metric_cols, selected_metrics.items()):
    column.metric(name, f"{value:.4f}")

left, right = st.columns(2)
with left:
    st.subheader("Confusion Matrix")
    cm = confusion_matrix(y_test, pred)
    fig, ax = plt.subplots(figsize=(5, 4))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", cbar=False, ax=ax,
                xticklabels=["Benign", "Malignant"], yticklabels=["Benign", "Malignant"])
    ax.set_xlabel("Predicted")
    ax.set_ylabel("Actual")
    st.pyplot(fig, clear_figure=True)

with right:
    st.subheader("Classification Report")
    report = classification_report(
        y_test, pred,
        target_names=["Benign", "Malignant"],
        output_dict=True,
        zero_division=0,
    )
    report_df = pd.DataFrame(report).transpose()
    st.dataframe(report_df.style.format("{:.4f}"), use_container_width=True)

st.subheader("Prediction results on uploaded test data")
result_output = df[[c for c in df.columns if c == "ID"]].copy()
result_output["Actual Diagnosis"] = y_test.map({0: "B", 1: "M"}).values
result_output["Predicted Diagnosis"] = pd.Series(pred, index=df.index).map({0: "B", 1: "M"}).values
result_output["Malignant Probability"] = prob
st.dataframe(result_output, use_container_width=True)
